#!/usr/bin/python3
from sys import argv

if len(argv) < 2:
    print("Usage: python script.py filename")
    exit()

with open(argv[1]) as f:
    for line in f:
        num = int(line)
        print("{:d}=".format(num), end='')

        if num % 2 == 0:
            print("{}*2".format(num//2))
            continue
        
        found_factor = False
        for i in range(3, num, 2):
            if num % i == 0:
                factor = num // i
                found_factor = True
                print("{}*{}".format(factor, i))
                break
        
        if not found_factor:
            print("Prime")
